apiVersion: v1
kind: Service
metadata:
  labels:
    component: techtrends
  name: techtrends
  namespace: {{ .Values.namespace }} 
spec:
  ports:
  - name: techtrends
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
