apiVersion: v1
kind: Service
metadata:
  labels:
    component: techtrends
  name: techtrends
  namespace: sandbox
spec:
  ports:
  - name: techtrends
    port: 4111
    protocol: TCP
    targetPort: 3111
  type: ClusterIP
